language: python
env:
  - DJANGO=1.7
  - DJANGO=1.8
python:
  - 2.7
  - 3.4
script: python setup.py test
notifications:
  email:
    - jussi.vaihia@futurice.com
install:
  - pip install Django==$DJANGO --use-mirrors
  - pip install django-dirtyfield
  - pip install diff-match-patch==20121119
